version: '3.7'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    networks:
      - default
      - shopnet

networks:
  shopnet:
    external: true
